### PR TITLE
add support for projects in nested folders

### PR DESCRIPTION
**Pull request by ghost**
Add support for nested projects, i.e.:

```
{
  "projects": {
    "foo": ""https://github.com/foo/foo"
    "foo/bar": "https://github.com/foo/bar",
  }
}
```

Currently `meta git clone` fails with:

> fatal: destination path 'foo' already exists and is not an empty directory.

### CODE REVIEW

**Comment by mateodelnorte** [comment]
This already works as intended. I have many `.meta` files with nested folders.

**Comment by ghost** [comment]
Hi, @mateodelnorte. Sorry, but it does not work in case, when git repositories are nested (both parent and nested folders have .git folder inside). Maybe I was not clear enough.

Please, take a look at the [following example](https://github.com/keinkonzept/meta-meta/blob/master/.meta):

```
$ meta git clone https://github.com/keinkonzept/meta-meta.git
meta git cloning into 'https://github.com/keinkonzept/meta-meta.git' at meta-meta

meta-meta:
Cloning into 'meta-meta'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
meta-meta ✓

/home/keinkonzept/meta/meta-meta/foo/bar:
Cloning into 'foo/bar'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
/home/archakov/meta/meta-meta/foo/bar ✓

/home/keinkonzept/meta/meta-meta/foo:
fatal: destination path 'foo' already exists and is not an empty directory.
/home/keinkonzept/meta/meta-meta/foo: command 'git clone https://github.com/keinkonzept/meta-foo.git foo' exited with error: Error: Command failed: git clone https://github.com/keinkonzept/meta-foo.git foo
```

In this case first `meta-foo-bar` is cloned creating folder structure `foo/bar`. Then there is an attempt to clone `meta-foo` into folder `foo` which already exists and not empty. This results in git error above.

meta just clones projects one by one and does not account for nesting. Coincidentally projects might be arranged in `.meta` file in correct nesting order top to bottom and `meta git clone` will work. Otherwise it fails.

**Comment by mateodelnorte** [comment]
You're missing a `.gitignore` file in your meta project. You must `.gitignore` every folder listed as a key in your `.meta` file's projects. See https://github.com/mateodelnorte/meta, itself.

**Comment by ghost** [comment]
Hi @mateodelnorte. `.gitignore` does not make any difference here. I've added it to meta project and the error is still there. The issue is really that the destination folder for the 2nd project is already created by checkout of the 1st project. That's why the current behavior `git clone ${gitUrl} ${folder}` fails as `${folder}` already exists.

If you still think that's not the case, please point me to a working meta project with similar structure.

**Comment by ghost** [comment]
In https://github.com/mateodelnorte/meta project are nested in `plugins/*` folder. But there is no project that has `plugins` folder itself as checkout destination.

**Comment by musculman** [comment]
I have the exactly same problem in my project. The suggested fix from @keinkonzept fixes it, but I'd rather not fork the project just for it.

**Comment by mateodelnorte** [comment]
If you already `git add`ed your folders to your repo, your `.gitignore` isn't going to make a difference... because you already added them. You need to `rm` them and `git rm` them. 

*don't do this unless you've already created your new repo with your files. If you want to make a new repo from the old folder that maintains all the original git history, use https://help.github.com/en/articles/splitting-a-subfolder-out-into-a-new-repository. 

If this was an actual problem, `meta git clone` would literally not work for *any* project. Many people use this project every day, and it works.

**Comment by mateodelnorte** [comment]
I notice your folder structure looks like this: 
``` 
meta
   top-child
      sub-child
```
You might want to consider using nested meta repos here. You can have a `.meta` file in your `top-child` dir, for instance, if you wanted something like the following: 
```
meta
  .meta
  infrastructure
    .meta
    infra-1
    infra-2
  services-dir
    .meta
    services-proj1
    services-proj2
  web
    .meta
    web-api
    web-site
```

**Comment by mateodelnorte** [comment]
After reading through, I realize I read this too quickly. I understand your issue now. 

My initial inclination is to wonder if what you actually want is to have nested .meta files and meta repos, as above. But I do agree having the tool be as flexible as possible is best. Apologies for the confusion. 

@patrickleet @aleclarson what are your opinions here?

**Comment by patrickleet** [comment]
seems like a nested .meta project thing - I've done this in the past a bunch

**Comment by musculman** [comment]
Hi, any update on this? Do you plan to merge it at some point? Thanks

**Comment by mateodelnorte** [comment]
@musculman, the conversation above is regarding whether we think it is a good idea to nest repos this way. The normally prescribed way of doing what your doing is to have nested meta repos, instead of having a single meta repo that forces the nesting. That would look like the structure I noted in https://github.com/mateodelnorte/meta-git/pull/47#issuecomment-521686745.

**Comment by musculman** [comment]
Thank you for the update, I understand about the above. But I don't know if you concluded that indeed you'd rather only support nested meta repos or you would also support a single meta repo with forced nesting.
If you would prefer the first option, my question would be: does this patch affect negatively that approach? Because if not, it could be merged and you could support both options, right?
Because of course I am not an expert on meta, I am asking about it as most likely I am missing something or some edge case that I do not know about. Thanks!

**Comment by musculman** [comment]
I guess the stale bot answered my question from September...

**Pull request closed without merging**
