### PR TITLE
chore: use pretty-quick

### PR DESCRIPTION
**Pull request by aleclarson**
Also included:
- minor refactoring of `lib/metaGitUpdate.js`

### CODE REVIEW

**Comment by patrickleet** [comment]
@aleclarson sorry - stale with SR pushes last night

**Comment by aleclarson** [comment]
No worries. Fixed!

**Comment by patrickleet** [comment]
@aleclarson tests still failed - says package-lock is out of sync

`rm -rf node_modules && rm package-lock.json && npm i`

**Comment by aleclarson** [comment]
@patrickleet We should re-generate `package-lock.json` in Travis, since Renovate handles lockfile updates.

**Comment by patrickleet** [comment]
idk if that makes sense - is that done elsewhere - the default install command in `npm ci` which relies on it existing.

it failed pretty hard at keeping meta's lockfile up to date with all the changes last night - there are like 8 PRs with merge conflicts

**Comment by aleclarson** [comment]
@patrickleet Renovate isn't enabled yet on most of these repos, I think.

**Comment by patrickleet** [comment]
yea not yet - i just meant on meta

**Comment by aleclarson** [comment]
Oh, okay. I don't see the merge conflicts you speak of.

PS: We should also set [`ignoreNpmrcFile`](https://renovatebot.com/docs/configuration-options/#ignorenpmrcfile) in `renovate.json` and then add a `.npmrc` that disable lockfile generation for contributors.

**Comment by patrickleet** [comment]
not a fan of disabling lockfiles - makes security scanning not work, also npm ci relies on it

**Comment by patrickleet** [comment]
with people compromising npm packages all the time, visibility into that is necessary

**Comment by mateodelnorte** [comment]
@aleclarson renovate should be enabled for pretty much all my repos.

**Comment by aleclarson** [comment]
@patrickleet Lockfiles would not be disabled. Just remove the noise from local development. I'm forced to do `git reset *lock*` after `git add .` when working on PRs. The lockfile would still exist, just not be updated during development (only in Travis before the PR is merged).

**Comment by patrickleet** [comment]
@aleclarson interested to see that setup - haven't done so that way before myself

**Comment by aleclarson** [comment]
@patrickleet Me neither. Just now stumbled on it. ;)

**Comment by aleclarson** [comment]
Even if I get Travis to update the lockfile, I still need an automated way to then include that updated lockfile with the PR, which Renovate could theoretically handle. Maybe I'll open an issue about that.

With that said, I'll just include an updated `package-lock.json` with my PRs from now on.

**Question:** Should we remove `yarn.lock`, since it may be out-of-sync? For example, if a contributor does a `git pull` **after** a PR that only updates `package-lock.json` is merged and **before** Renovate's PR that updates `yarn.lock` to match.

Lastly, it might be worth keeping an eye on this: https://github.com/renovatebot/renovate/issues/1342

**Comment by patrickleet** [comment]
@aleclarson even yarn advises to only use one

**Comment by patrickleet** [comment]
I think generally on most days it won't be an issue - only when there is a flurry of activity does it get out of sync, and in which case it takes like 15 seconds to generate a new one

**Comment by aleclarson** [comment]
@patrickleet Aside from that, I don't see what problem having both `yarn.lock` and `package-lock.json` solves. Contributors will only _need_ a lockfile when they are trying to reproduce a bug on their machine. In that case, just use `npm install` temporarily.

**Comment by aleclarson** [comment]
Updated `package-lock.json`

**Comment by aleclarson** [comment]
> @mateodelnorte says: "renovate should be enabled for pretty much all my repos."

The @renovate bot should instantly send a pull request to any repos it's enabled for.

I checked meta-git, meta-project, and meta-exec real quick, and the bot hasn't sent any PRs. So you should probably double check. 😅

**Pull request merged**
